//
//  NextBirdWatchStyleKit.h
//  nextBirdWatch
//
//  Created by Blake McMillian on 11/28/14.
//  Copyright (c) 2014 NeXT. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

IB_DESIGNABLE

@interface NextBirdWatchStyleKit : NSObject

// Drawing Methods
+ (void)drawRootBackgroundView;
+ (void)drawRootViewTextFieldContainerWithTextFieldWasSelected: (BOOL)textFieldWasSelected;
+ (void)drawSearchButtonCanvasImageWithSearchButtonWasPressed: (BOOL)searchButtonWasPressed;
+ (void)drawRegexSearchButtonCanvasImageWithRegexButtonWasPressed: (BOOL)regexButtonWasPressed;
+ (void)drawMapButtonCanvasImageWithMapButtonWasPressed: (BOOL)mapButtonWasPressed;

@end



@interface NSShadow (PaintCodeAdditions)

+ (instancetype)shadowWithColor: (UIColor*)color offset: (CGSize)offset blurRadius: (CGFloat)blurRadius;
- (void)set;

@end
