source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'STTwitter'
pod 'Google-Maps-iOS-SDK', '~> 1.9.0'
pod 'Canvas', '~> 0.1.2'
pod 'pop', '~> 1.0.7'
pod "AMPActivityIndicator"
pod 'Regexer', '~> 1.3.1'
pod 'PNChart', '~> 0.5.5'
pod 'FLAnimatedImage', '~> 1.0'
pod 'SDWebImage', '~>3.6'
